language: android
dist: trusty
android:
 components:
  - tools # to get the new `repository-11.xml`
  - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
  - platform-tools
  - build-tools-29.0.2
  - android-29
  - sys-img-x86-android-26
before_install:
 - yes | sdkmanager "platforms;android-29"
 - chmod +x gradlew
script:
 - ./gradlew build connectedCheck